version: '3.7'
services:
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5901:5900
  unit-tests:
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    build:
      dockerfile: rspec.dockerfile
      context: .
    volumes:
      - ".:/app"
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb
  website:
   build:
    context: .
   ports:
    - 80:80
