name: First challenge

on: push

jobs:
    ubuntu:
        name: First job
        runs-on: ubuntu-latest
        steps:
        - run:  date
    windows:
        name: Second job
        runs-on: windows-latest
        steps:
        - run: date
    macos:
        name: Third job
        runs-on: macos-latest
        steps:
        - run: date
    depends:
        name: Fourth job
        runs-on: ubuntu-latest
        needs: [ubuntu, windows, macos]
        steps:
        - run: date